docs: update plugin docs.
laanwj/rust-clightning-rpc pull request #35
Opened 2022-06-11 11:15 UTC by swaptr

Better docs and readme.

2022-06-11 13:07 UTC, vincenzopalazzo requested changes
Thanks to looking inside this type of docs, your comments are very helpful.

I know that it is not finished, but I add some comments on it

2022-06-11 13:07 UTC, vincenzopalazzo commented on plugin/examples/foo_plugin.rs
> +// FIXME: Since people will refer to this file to understand usage, it needs some interesting documentation.
very good point, thanks :)

2022-06-11 13:07 UTC, vincenzopalazzo commented on plugin/src/commands/json_utils.rs
> +//! author: https://github.com/vincenzopalazzo
```suggestion
//! author: https://github.com/vincenzopalazzo
// FIXME: maybe this can be moved in the common crater?
```

2022-06-11 13:07 UTC, vincenzopalazzo commented on plugin/src/commands/json_utils.rs
> +/// This function adds a string value to the JSON payload.
```suggestion
/// adds a string value to the JSON payload.
```

2022-06-11 13:07 UTC, vincenzopalazzo commented on plugin/src/commands/json_utils.rs
> +/// This function adds an 64-bit integral value to the JSON payload.
```suggestion
/// adds an 64-bit integral value to the JSON payload.
```

2022-06-11 13:07 UTC, vincenzopalazzo commented on plugin/src/commands/json_utils.rs
> +/// This function returns a success response.
```suggestion
/// returns a success response.
```

2022-06-11 13:07 UTC, vincenzopalazzo commented on plugin/src/commands/json_utils.rs
> +/// This function is used to initialize the JSON payload as an empty JSON object.
```suggestion
/// return a server::json_value useful to initialize the JSON payload as an empty JSON object.
```

2022-06-11 13:07 UTC, vincenzopalazzo commented on plugin/src/commands/json_utils.rs
> +/// This function adds a string value to the JSON payload.
same also in all the place

2022-06-11 13:07 UTC, vincenzopalazzo commented on plugin/src/commands/mod.rs
> +//! FIX: ADD A DESCRIPTION FOR THIS FILE.
```suggestion
//! FIXME: add more description for this module
```

2022-06-11 13:07 UTC, vincenzopalazzo commented on plugin/src/commands/types.rs
> +//! core plugin library.
```suggestion
//! core plugin library.
//! It is a rust implementation of the command pattern, and it is an OOP implementation of a callback
```

2022-09-24 22:30 UTC, vincenzopalazzo commented
have you intention to finish it? or I can close?

2022-09-26 04:37 UTC, swaptr commented
I have tried improving the documentation to my best. You had already done a great job in improving rest of the docs.

2022-09-26 14:23 UTC, merged